# Site settings
title: Magento 2 Bootcamp Cheatcheet
email: ray@supportdesk.nu
description: >
  Magento 2 Bootcamp Cheatcheet
description-short: >
  Learn, Act, Commit
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cheatsheet.nu" # the base hostname & protocol for your site
paginate:	5

name: 'Ray Bogman'
bio: > 
  Ray Bogman is an IT professional and Magento evangelist from the Netherlands.

author_image: "/assets/images/raybogman.png"
twitter_username: raybogman
github_username:  raybogman

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
